theme: jekyll-theme-cayman

title: 法拉的小说
description: 法拉的小说
locale: zh-CN
author: 法拉
sass:
  style: compressed

lsi: true
profile: true

defaults:
  - scope:
      path: ""
    values:
      layout: "functional"
  - scope:
      path: "_posts"
    values:
      layout: "novel"
      author: 法拉
      locate: zh-CN
      cc-type: by-nc-sa
      permalink: /:year/:categories/:title/
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
 - README.MD
 - CONTRIBUTING.MD
 - CODE_OF_CONDUCT.MD
 - Gemfile
 - Gemfile.lock

i18n:
  writing: 正在创作
  trailers: 预告
  done: 已完成
  discuss: 杂谈
  settings: 设定/世界观
# hide: 隐藏
# spark: 草案
# novel: 小说

nav-shortname:
  有关我的小说进度，Kurzgesagt和刘慈欣: 有关Kurzgesagt...
